version: '3.8'

services:

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always 
    volumes:
      - ./mqtt:/mosquitto/config
    ports:
      - 1883:1883

  telegraf: 
    image: telegraf:latest
    restart: unless-stopped
    volumes:
      - ./telegraf.config:/etc/telegraf/telegraf.conf
    depends_on:
      - mqtt
      - tsdb
    
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - tsdb

  tsdb:
    build:
      dockerfile: ./tsdb/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=projectdb
    volumes:
      - ./tsdb/data:/var/lib/postgresql/data
      - ./tsdb/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - 5432:5432


    

    